/**
 * 蓝瓷女仆 · Azure Maid —— 语义 token(构建产物,请勿手工编辑)
 * ============================================================================
 * 由 scripts/build-tokens.mjs 生成。改配色请改 theme/palette.mjs 后运行 npm run build。
 *
 * 每个 token 在亮/暗两套里各有一个值,正好对应 theme.overrideTokens 的
 * { light, dark } 契约 —— 因此"亮色 / 暗色 / 跟随系统"三种偏好共用同一层
 * 覆盖:偏好为 system 时由主题服务按系统色决定用哪一套,颜色自动跟随。
 *
 * 不要把这套值写进 CSS 的 :root —— overrideTokens 负责行内样式,本文件是
 * 它的数据源,不是样式表。
 */

/** 亮色档:90 个语义 token。 */
export const LIGHT = Object.freeze({
  '--dsw-alias-bg-base': '#F4F7FE',
  '--dsw-alias-bg-layer-1': '#FFFFFF',
  '--dsw-alias-bg-layer-2': '#E9EFFB',
  '--dsw-alias-bg-layer-3': '#FFFFFF',
  '--dsw-alias-bg-module-platform': '#EDF2FC',
  '--dsw-alias-bg-multi-select': '#EDF2FC',
  '--dsw-alias-bg-overlay': '#DEE7F8',
  '--dsw-alias-bg-skeleton': '#0000000A',
  '--dsw-alias-bg-mask-1': '#0000003D',
  '--dsw-alias-bg-mask-2': '#0000001F',
  '--dsw-alias-bg-mask-3': '#0000007A',
  '--dsw-alias-bg-mask-photo': '#000000E0',
  '--dsw-alias-bg-mask-drop': '#FFFFFFB3',
  '--dsw-alias-border-l1': '#2A35680F',
  '--dsw-alias-border-l2': '#2A356826',
  '--dsw-alias-border-l2-darkmode-thin': '#2A35681F',
  '--dsw-alias-border-l3': '#2A356833',
  '--dsw-alias-border-l4': '#2A356840',
  '--dsw-alias-border-inverted': '#00000000',
  '--dsw-alias-border-inverted2': '#00000000',
  '--dsw-alias-label-primary': '#141C36',
  '--dsw-alias-label-primary-bluish': '#1E2A52',
  '--dsw-alias-label-primary-dimmed': '#101731',
  '--dsw-alias-label-primary-foreground': '#FFFFFF',
  '--dsw-alias-label-primary-inverted': '#FFFFFF',
  '--dsw-alias-label-secondary': '#3F4B78',
  '--dsw-alias-label-tertiary': '#5A648F',
  '--dsw-alias-label-caption': '#767FA6',
  '--dsw-alias-label-dimmed': '#C3CFE8',
  '--dsw-alias-brand-primary': '#3A4A8C',
  '--dsw-alias-brand-primary-invert': '#141C36',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#276C9F',
  '--dsw-alias-brand-text': '#141C36',
  '--dsw-alias-link': '#2F6FB0',
  '--dsw-alias-button-primary-fill': '#3A4A8C',
  '--dsw-alias-button-primary-hover': '#4A5BA6',
  '--dsw-alias-button-primary-dimmed': '#D6E3F8',
  '--dsw-alias-button-contrast-fill': '#3F4B78',
  '--dsw-alias-button-elevated-fill': '#FFFFFF',
  '--dsw-alias-button-floating-fill': '#FFFFFF',
  '--dsw-alias-button-floating-hover': '#F4F7FE',
  '--dsw-alias-button-ghost-active-fill': '#D2DFF6',
  '--dsw-alias-button-ghost-active-border': '#4A5BA6',
  '--dsw-alias-button-ghost-active-hover': '#BDD1F2',
  '--dsw-alias-button-info-fill': '#276C9F',
  '--dsw-alias-button-info-hover': '#2F6FB0',
  '--dsw-alias-button-tool-bar-fill': '#54555780',
  '--dsw-alias-button-tool-bar-fill-invisible': '#1F1F1F5C',
  '--dsw-alias-button-tool-bar-hover': '#54555799',
  '--dsw-alias-interactive-bg-hover': '#2432560F',
  '--dsw-alias-interactive-bg-hover-solid': '#F4F7FE',
  '--dsw-alias-interactive-bg-hover-accent': '#276C9F24',
  '--dsw-alias-interactive-bg-hover-danger': '#E0416A12',
  '--dsw-alias-interactive-bg-active': '#24325626',
  '--dsw-alias-state-business-primary': '#276C9F',
  '--dsw-alias-state-business-tertiary': '#D6E3F8',
  '--dsw-alias-state-success-primary': '#1A7B61',
  '--dsw-alias-state-success-secondary': '#1A7B61',
  '--dsw-alias-state-success-tertiary': '#DEF4EA',
  '--dsw-alias-state-warn-primary': '#936511',
  '--dsw-alias-state-warn-secondary': '#936511',
  '--dsw-alias-state-warn-tertiary': '#FBF0D8',
  '--dsw-alias-state-warn-label': '#8A5E0E',
  '--dsw-alias-state-error-primary': '#B83551',
  '--dsw-alias-state-error-secondary': '#B83551',
  '--dsw-alias-markdown-code-block': '#EDF2FC',
  '--dsw-alias-markdown-code-block-banner': '#DCE6F9',
  '--dsw-alias-markdown-code-segment-selected': '#FFFFFF',
  '--dsw-alias-markdown-code-segment-unselected': '#E9EFFB',
  '--dsw-alias-markdown-inline-code': '#E4EBF9',
  '--dsw-alias-markdown-placeholder': '#E9EFFB',
  '--dsw-alias-markdown-tag': '#DFE8F8',
  '--dsw-alias-markdown-citation': '#DCE6F8',
  '--dsw-alias-scrollbar-bg-l1': '#DFE7F6',
  '--dsw-alias-scrollbar-bg-l2': '#DFE7F6',
  '--dsw-alias-scrollbar-hover-l1': '#C3CFE8',
  '--dsw-alias-scrollbar-hover-l2': '#A6B6DC',
  '--dsw-alias-toast-bg': '#1B2444',
  '--dsw-alias-tooltip-bg': '#1B2444',
  '--dsw-specific-bubble': '#EAF0FC',
  '--dsw-specific-bubble-highlight': '#CEDDF6',
  '--dsw-specific-input-major': '#FFFFFF',
  '--dsw-specific-login-input': '#F4F7FE',
  '--dsw-specific-menu': '#FFFFFF',
  '--dsw-specific-selector': '#EDF2FC',
  '--dsw-specific-sidebar-fill': '#E7EEFA',
  '--dsw-specific-sidebar-nav-item-hover': '#F4F7FE',
  '--dsw-specific-sidebar-nav-item-active': '#D2DFF6',
  '--dsw-specific-sidebar-nav-item-active-accent': '#BDD1F2',
  '--dsw-specific-tip': '#EDF2FC',
})

/** 暗色档:90 个语义 token。 */
export const DARK = Object.freeze({
  '--dsw-alias-bg-base': '#0A1024',
  '--dsw-alias-bg-layer-1': '#151E42',
  '--dsw-alias-bg-layer-2': '#1D2750',
  '--dsw-alias-bg-layer-3': '#1D2750',
  '--dsw-alias-bg-module-platform': '#1B2549',
  '--dsw-alias-bg-multi-select': '#1B2549',
  '--dsw-alias-bg-overlay': '#2E3C74',
  '--dsw-alias-bg-skeleton': '#FFFFFF14',
  '--dsw-alias-bg-mask-1': '#00000080',
  '--dsw-alias-bg-mask-2': '#00000033',
  '--dsw-alias-bg-mask-3': '#0000007A',
  '--dsw-alias-bg-mask-photo': '#000000E0',
  '--dsw-alias-bg-mask-drop': '#272730B3',
  '--dsw-alias-border-l1': '#FFFFFF0F',
  '--dsw-alias-border-l2': '#FFFFFF1F',
  '--dsw-alias-border-l2-darkmode-thin': '#FFFFFF0F',
  '--dsw-alias-border-l3': '#FFFFFF29',
  '--dsw-alias-border-l4': '#FFFFFF33',
  '--dsw-alias-border-inverted': '#FFFFFF0F',
  '--dsw-alias-border-inverted2': '#FFFFFF14',
  '--dsw-alias-label-primary': '#E8EEFB',
  '--dsw-alias-label-primary-bluish': '#E8EEFB',
  '--dsw-alias-label-primary-dimmed': '#E8EEFB',
  '--dsw-alias-label-primary-foreground': '#0A1024',
  '--dsw-alias-label-primary-inverted': '#1D2750',
  '--dsw-alias-label-secondary': '#A9B7E0',
  '--dsw-alias-label-tertiary': '#8A9AD8',
  '--dsw-alias-label-caption': '#6E7CB4',
  '--dsw-alias-label-dimmed': '#2E3C74',
  '--dsw-alias-brand-primary': '#8A9AD8',
  '--dsw-alias-brand-primary-invert': '#E8EEFB',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#7FC0E8',
  '--dsw-alias-brand-text': '#E8EEFB',
  '--dsw-alias-link': '#8FBEF0',
  '--dsw-alias-button-primary-fill': '#8A9AD8',
  '--dsw-alias-button-primary-hover': '#B9C5EC',
  '--dsw-alias-button-primary-dimmed': '#27336A',
  '--dsw-alias-button-contrast-fill': '#E8EEFB',
  '--dsw-alias-button-elevated-fill': '#2E3C74',
  '--dsw-alias-button-floating-fill': '#1B2549',
  '--dsw-alias-button-floating-hover': '#1D2750',
  '--dsw-alias-button-ghost-active-fill': '#2E3C74',
  '--dsw-alias-button-ghost-active-border': '#2E3C74',
  '--dsw-alias-button-ghost-active-hover': '#B9C5EC',
  '--dsw-alias-button-info-fill': '#7FC0E8',
  '--dsw-alias-button-info-hover': '#8FBEF0',
  '--dsw-alias-button-tool-bar-fill': '#54555780',
  '--dsw-alias-button-tool-bar-fill-invisible': '#1F1F1F5C',
  '--dsw-alias-button-tool-bar-hover': '#54555799',
  '--dsw-alias-interactive-bg-hover': '#FFFFFF14',
  '--dsw-alias-interactive-bg-hover-solid': '#1B2549',
  '--dsw-alias-interactive-bg-hover-accent': '#FFFFFF3D',
  '--dsw-alias-interactive-bg-hover-danger': '#F25A5A26',
  '--dsw-alias-interactive-bg-active': '#FFFFFF24',
  '--dsw-alias-state-business-primary': '#8A9AD8',
  '--dsw-alias-state-business-tertiary': '#2E3C74',
  '--dsw-alias-state-success-primary': '#5FD6B4',
  '--dsw-alias-state-success-secondary': '#5FD6B4',
  '--dsw-alias-state-success-tertiary': '#173A44',
  '--dsw-alias-state-warn-primary': '#F0C168',
  '--dsw-alias-state-warn-secondary': '#F0C168',
  '--dsw-alias-state-warn-tertiary': '#33294A',
  '--dsw-alias-state-warn-label': '#F2A9BE',
  '--dsw-alias-state-error-primary': '#FF8598',
  '--dsw-alias-state-error-secondary': '#FF8598',
  '--dsw-alias-markdown-code-block': '#161F42',
  '--dsw-alias-markdown-code-block-banner': '#27336A',
  '--dsw-alias-markdown-code-segment-selected': '#27336A',
  '--dsw-alias-markdown-code-segment-unselected': '#161F42',
  '--dsw-alias-markdown-inline-code': '#1B2549',
  '--dsw-alias-markdown-placeholder': '#1D2750',
  '--dsw-alias-markdown-tag': '#1B2549',
  '--dsw-alias-markdown-citation': '#2E3C74',
  '--dsw-alias-scrollbar-bg-l1': '#27336A',
  '--dsw-alias-scrollbar-bg-l2': '#27336A',
  '--dsw-alias-scrollbar-hover-l1': '#3A4A8C',
  '--dsw-alias-scrollbar-hover-l2': '#4A5BA6',
  '--dsw-alias-toast-bg': '#C6D2EE',
  '--dsw-alias-tooltip-bg': '#C6D2EE',
  '--dsw-specific-bubble': '#1B2549',
  '--dsw-specific-bubble-highlight': '#27336A',
  '--dsw-specific-input-major': '#1B2549',
  '--dsw-specific-login-input': '#0A1024',
  '--dsw-specific-menu': '#1D2750',
  '--dsw-specific-selector': '#1D2750',
  '--dsw-specific-sidebar-fill': '#0D1430',
  '--dsw-specific-sidebar-nav-item-hover': '#1B2549',
  '--dsw-specific-sidebar-nav-item-active': '#2A366B',
  '--dsw-specific-sidebar-nav-item-active-accent': '#43549B',
  '--dsw-specific-tip': '#1B2549',
})

/** 亮暗两档的 token 名完全一致 —— 覆盖层只切值,不切名单。 */
export const TOKEN_NAMES = Object.freeze(Object.keys(LIGHT))
